### ISSUE TITLE
Support Windows ARM64

### ISSUE THREAD

**Issue by sappho192** [sappho192/Tokenizers.DotNet#13]
#12

**Comment by sappho192** [comment]
Hi @Binozo ,

Today I've tried everything to run ARM64 Windows on my x64 Windows (QEMU, VirtualBox) and Oracle Cloud ARM image but nothing worked ._.)

Can you pull the latest commit of this main branch ( 70252f1 ) and run the `build_all_clean.ps1`?
If you have succeeded to build `Tokenizers.DotNet.runtime.win-arm64.1.1.0.nupkg` in `nuget\win-arm64`, it would be appreciated if you send it to my email (you can check my address from my Github profile).

Before the Github Actions offically support Windows ARM64, maybe I need you to request win-arm64 artifacts every time. (Sorry about that)
https://github.com/actions/runner-images/issues/10820#issuecomment-2431006748

**Comment by Binozo** [comment]
Yeah sure no problem!

I built the nupkg and sent it to you via email.
Just ping me if you need a new build again 🧑‍💻

And thanks for you effort in this project, without it I couldn't develop mine currently 😄

**Comment by sappho192** [comment]
Hi @Binozo , thank you for your help too 😊

I've received your mail, and just released 1.1.0. (Thank you again!)
So could you check if ARM64 native library also work properly?

The ID of ARM64 package is `Tokenizers.DotNet.runtime.win-arm64`.
Install both `Tokenizers.DotNet` and `Tokenizers.DotNet.runtime.win-arm64` to your project and it should work.

**Comment by Binozo** [comment]
Hey @sappho192 

I installed both `Tokenizers.DotNet` and `Tokenizers.DotNet.runtime.win-arm64` and could confirm it working  🚀🚀🚀

Thank you for the quick release and have a nice weekend ☀️

**Comment by sappho192** [comment]
@Binozo glad to hear that 👍

Have a nice weekend, too! Dankeschön!
